sudo: false
language: go
go:
  - 1.5.1
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/lint/golint
script:
  - golint
  - go test -coverprofile=coverage.out
  - go tool cover -func=coverage.out
